// Configuration Supabase - clés publiques uniquement
const SUPABASE_URL = "https://rudikjbpfvpklduumzkw.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1ZGlramJwZnZwa2xkdXVtemt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2NDI5NTAsImV4cCI6MjEwMjIxODk1MH0.ViVo0BtQBHeubXkdQ-o93UlmV6hDlSzcu-8GmEkuCpo";
